### ISSUE TITLE
[FEATURE] Feature to have the site on Spanish

### ISSUE THREAD

**Issue by samc18** [samc18/my-finances-checker#49]
**Describe the solution you'd like**
A great feature will be to add the Spanish language to the site and also the Peruvian local currency. There needs to be a selector to change the language and the language selected must be stored in local storage to improve UX.

**Comment by adrianmarinwork** [comment]
Hey, I can take care of this if you want, I'm from Spain :D
One question, how do you want to handle the translations?

**Comment by samc18** [comment]
hi @adrianmarinwork! **I'm really sorry**, I had the branch with the feature ready to merge. I didn't read your comment on time. **Thanks** for taking an interest in working on this project. If you are still looking to be involved you are more than welcome to review the current language feature and check for improvements or mistakes perhaps.
