### ISSUE TITLE
[BUG] Fix links

### ISSUE THREAD

**Issue by samc18** [samc18/my-finances-checker#51]
**Describe the bug**
Links and clickable elements only have the pointer cursor as a reference of an interactive element. They should also have a hover and focus effect.

**Comment by AlfiyaSiddique** [comment]
Hello !!

I want to work on this issue, please help me set up this project on my local machine. 
I already forked and cloned it.  How can I compile and run the react app?

**Comment by samc18** [comment]
hi, @AlfiyaSiddique thanks for taking an interest in this project. Sorry for the delayed response. It's pretty straightforward to set up. The project was created with [Vite](https://vitejs.dev/guide/). After cloning the repo you need to run `npm install`, and make sure you are inside the project folder, to install all the dependencies. After the installation has been completed you need to run `npm run dev` to be able to display the project, a blue link will appear and when you click it it will open a new tab on the browser with the project.

If you run into any issues please feel free to reach out.

**Comment by AlfiyaSiddique** [comment]
Thanks **@samc18**  for the response.
