### ISSUE TITLE
[BUG] Savings logic is incorrect

### ISSUE THREAD

**Issue by samc18** [samc18/my-finances-checker#52]
**Describe the bug**
Budget amounts should be allowed to be over the max amount established by the 50/30/20 rule since is always better to save more. Currently, if the savings amount is over the max amount is displayed as over the budget and in red.

**Expected behavior**
If the savings amount is less than the respective amount it should be displayed as under budget but in red to encourage more savings. If the amount is over the max amount it should be displayed in green.

**Screenshots**
![image](https://user-images.githubusercontent.com/93607710/205159068-0f328283-cacd-4208-89b7-69ccae616cf9.png)

**Comment by adrianmarinwork** [comment]
Hey I can take care of this if you want!

**Comment by samc18** [comment]
Sure, go ahead!
